CREATE DATABASE CLINICA ;
USE CLINICA;
CREATE TABLE AMBULATORIOS(
id int auto_increment PRIMARY KEY
,NOROA INT NOT NULL
,ANDAR NUMERIC(3,0)NOT NULL
,CAPACIDADE SMALLINT NOT NULL
);
CREATE TABLE MEDICOS(
id int auto_increment PRIMARY KEY
,CODM INT NOT NULL
,NOME VARCHAR(40) NOT NULL
,IDADE SMALLINT NOT NULL
,ESPECIALIDADE CHAR(20)
,CPF NUMERIC(11)UNIQUE
,CIDADE VARCHAR(30)NOT NULL
,NROA INT NOT NULL
,ID_AMB INT NOT NULL
,FOREIGN KEY(ID_AMB)REFERENCES AMBULATORIOS(id)
);

